//
//  VerifyCodeRouter.swift
//  BeCareful
//
//  Created by Mariana Parente on 24/08/20.
//  Copyright (c) 2020 Jose Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VerifyCodeRoutingLogic {
    func goToHome()
}

protocol VerifyCodeDataPassing {
    var dataStore: VerifyCodeDataStore? { get }
}

class VerifyCodeRouter: NSObject, VerifyCodeRoutingLogic, VerifyCodeDataPassing {
    weak var viewController: VerifyCodeViewController?
    var dataStore: VerifyCodeDataStore?
    
    // MARK: Routing
    func goToHome() {
        AppDelegate.sharedInstance.loadHome()
    }

}
