//
//  VerifyCodePresenter.swift
//  BeCareful
//
//  Created by Mariana Parente on 24/08/20.
//  Copyright (c) 2020 Jose Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol VerifyCodePresentationLogic {
    func presentNumber(response: VerifyCode.DataPhoneNumber.Response)
    func presentError(response: VerifyCode.RegisterSuccess.Response)
    func presentRegisterSuccess()
}

class VerifyCodePresenter: VerifyCodePresentationLogic {
    weak var viewController: VerifyCodeDisplayLogic?
    
    // MARK: Actions
   func presentNumber(response: VerifyCode.DataPhoneNumber.Response) {
    let title = "Ingresa el código de 11 dígitos enviado al \(response.phoneNumber)"
        let viewModel = VerifyCode.DataPhoneNumber.ViewModel(title: title)
        viewController?.displayPhoneNumber(viewModel: viewModel)
    }

    func presentRegisterSuccess() {
        viewController?.displayRegisterComplete()
    }

    func presentError(response: VerifyCode.RegisterSuccess.Response) {
        let viewModel = VerifyCode.RegisterSuccess.ViewModel(errorMessage: response.errorMessage)
        viewController?.displayError(viewModel: viewModel)
    }
}
